//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareFixingApp.Entityframework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurrencyCalculatorEntities : DbContext
    {
        public CurrencyCalculatorEntities()
            : base("name=CurrencyCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CapitalBackup> CapitalBackups { get; set; }
        public DbSet<CurrencyName> CurrencyNames { get; set; }
        public DbSet<FCAverageRate> FCAverageRates { get; set; }
        public DbSet<LoanDetail> LoanDetails { get; set; }
        public DbSet<LoanTaker> LoanTakers { get; set; }
        public DbSet<SalePurchase> SalePurchases { get; set; }
        public DbSet<ShareHolder> ShareHolders { get; set; }
        public DbSet<SHProfitDetail> SHProfitDetails { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
