//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareFixingApp.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        public int Id { get; set; }
        public int LoanTakerId { get; set; }
        public double Amount { get; set; }
        public bool IsReceivable { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Description { get; set; }
        public Nullable<int> LoanType { get; set; }
    
        public virtual LoanTaker LoanTaker { get; set; }
    }
}
