//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareFixingApp.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHProfitDetail
    {
        public int Id { get; set; }
        public decimal Profit { get; set; }
        public int ShareHolderId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public decimal TodayShare { get; set; }
    
        public virtual ShareHolder ShareHolder { get; set; }
    }
}
